# camera description, for camera selection GUI and apps
# camera_class should be the manufacturer's name
#
camera_class:           "Raptor"
camera_model:	 	"OWL SWIR 640"
camera_info:	 	"640x512 (single ch., freerun)"

# rbtfile specifies the FPGA file to be loaded (almost always aiag.bit), for
# boards that have a separate UI FPGA.  This includes most non-cameralink
# boards and PCI DV FOX but not PCIe DV FOX. The directive will be ignored
# on boards that employ a single combined PCIe/UI FPGA.
#
rbtfile:		aiag.bit

# actual width/height (total pixels) and depth of data from camera
# to only grab high 8-bits, set depth to 8 but leave extdepth set
# to actual depth, and adjust shift and mask accordingly
#
width:			640
height:			512
depth:			14
extdepth:		14

# shift register bits (hex):
# 0-3: value to barrel-shift data bits if cable not wired straight-thru
# 4: do aia swap of data bits end for end
# 5-7: undefined
#
shift:			00

# mask register bits (hex)
# any bits NOT set will be set to 0 in image
# set to match depth of camera
#
mask:			3fff

# interlace method
# only for interleaved and some dual channel cameras
# determines how image is deinterleaved for display -- WORD_INTLV is only
# one of many available methods -- see *_INTLV in pdv_dependent.h and
# camera configuration guide for more
#
#method_interlace:	WORD_INTLV

pclock_speed: 40

# wait for 20 seconds before timing out
user_timeout: 20000
